[build]
bin = "main"
cmd = "go build -gcflags 'all=-N -l' -o main ./cmd/ptm/main.go"
dir = "."
exclude_dir = ["vendor"]
include_ext = ["go"]
exclude_ext = ["md"]

[log]
level = "debug"

[serve]
cmd = "dlv --listen=:40000 --headless --api-version=2 --accept-multiclient exec ./main"
gracefull = true
bin_delay = 2000