[build]
bin = "main"
cmd = "dlv debug ./cmd/ptm/main.go --headless --listen=:40000รง --api-version=2 --accept-multiclient"
dir = "."
exclude_dir = ["vendor"]
include_ext = ["go"]
exclude_ext = ["md"]

[log]
level = "debug"

[serve]
cmd = "./main"
gracefull = true
bin_delay = 2000