version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: ptm-app
    ports:
      - "8080:8080"
      - "40000:40000"
    environment:
      DEBUG: "false"
      APP_ENV: docker
      APP_PORT: 8080
      DATABASE_URL: ${DOCKER_DATABASE_URL}
      REDIS_ADDR: ${DOCKER_REDIS_ADDR}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_DB: ${REDIS_DB}
      OTEL_EXPORTER_OTLP_ENDPOINT: http://telemetry:4317
      OTEL_RESOURCE_ATTRIBUTES: service.name=ptm-app
      OTEL_TRACES_SAMPLER: always_on
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      telemetry:
        condition: service_healthy

  db:
    image: postgres:15
    container_name: ptm-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ptmdb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: ptm-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  telemetry:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: ptm-otel-collector
    volumes:
      - ./configs/telemetry.yaml:/etc/otel-collector-config.yaml
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    ports:
      - "4317:4317"
      - "4318:4318"
    depends_on:
      jaeger:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "grpc_health_probe", "-addr=localhost:4317"]
      interval: 10s
      timeout: 5s
      retries: 3

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: ptm-jaeger
    ports:
      - "16686:16686"
      - "4316:4317"
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:16686"]
      interval: 10s
      timeout: 5s
      retries: 3